name: ike
version: '2.2.1'
summary: The Shewsoft VPN Manager
description: |
 The Shrew Soft VPN Client is a free IPsec VPN Client for FreeBSD, NetBSD,
 Linux and Windows operating systems. This product can be used to communicate
 with Open Source VPN servers (e.g. ipsec-tools) as well as some commercial
 VPN servers.
 .
 This package provides the connection manager program, which allows one
 to create, manage and use VPN connections.

grade: devel
confinement: devmode

apps:
  ikec:
    command: bin/ikec
  iked:
    daemon: simple
    command: sbin/iked
  qikea:
    command: bin/qikea
    desktop: bin/desktop-launch $SNAP/bin/qikea
  qikec:
    command: bin/qikec
    desktop: bin/desktop-launch $SNAP/bin/qikec

parts:
  ike:
    source: http://ftp.osuosl.org/pub/ubuntu/pool/universe/i/ike/ike-qtgui_2.2.1+dfsg-2ubuntu1_amd64.deb
    source-type: deb
    plugin: dump
    stage-packages:
      - ike
      - ike-qtgui
      - ipsec-tools
      - libmng2
      - libmysqlclient20
      - libqt4-dbus
      - libqt4-declarative
      - libqt4-network
      - libqt4-script
      - libqt4-sql
      - libqt4-sql-mysql
      - libqt4-xml
      - libqt4-xmlpatterns
      - libqtcore4
      - libqtdbus4
      - libqtgui4
      - mysql-common
      - qdbus
      - qt-at-spi
      - qtchooser
      - qtcore4-l10n
